### ISSUE TITLE
pexpect.spawn(logfile=sys.stdout) fails on python3.4, clarify documentation to use sys.stdout.buffer.

### ISSUE THREAD

**Issue by rich-pixley** [pexpect/pexpect#159]
File "/usr/lib/python3.4/site-packages/pexpect/__init__.py", line 904, in _log
    self.logfile.write(s)
TypeError: must be str, not bytes

This contradicts the doc.

**Comment by jquast** [comment]
This is why modules such as "six" or the py2to3 tool exist, and I highly encourage you to use it. The need for using str('text') in both python2 and 3, and being bytes-only for the former and unicode-only for the latter, and wishing your upstream API's to do the same is a path that will only lead to UnicodeDecodeError.

**Comment by Nodd** [comment]
Why not add a ```encoding``` argument to ```spawn``` ? By default it would be set to ```None```, which would mean no encoding is done, so that it accepts and returns bytes. If it is set to a string like ```"ascii"``` or ```"utf-8"```, then conversions are done exactly like in ```spawnu```. This would remove the need to separate the classes and improve discovery of this option (```spawnu``` is buried deep down in the documentation). ```errors``` could be added too with no harm.
```spawnu``` would become an alias for ```spawn``` for compatibility.

**Comment by takluyver** [comment]
That's actually not a bad idea - represent bytes/unicode as states within the class rather than separate classes. I have found the class hierarchy in Pexpect somewhat awkward, since for each kind of thing, there ought to be a bytes class and a corresponding unicode class (see e.g. PR #172). It would also be roughly similar to the behaviour of Py3 `open()`, which can open files either in bytes mode or text mode. On the other hand, `open()` is a function, and returns different classes based on which mode you specify, whereas `spawn` is a class itself.

@jquast , I'd welcome a second opinion.

**Comment by jquast** [comment]
agreed, i like the ``encoding`` argument proposal rather than the class taxonomies

**Comment by takluyver** [comment]
Great. I will aim to get round to that soon.

**Comment by rich-pixley** [comment]
That doesn't help me nor the problem I'm trying to report.  While it might make for a cleaner architecture, it doesn't seem to provide any functionality that doesn't already exist.  I'd argue that it's arbitrary make-work and your time would be better spent elsewhere.

I don't mind that there are bytes and unicode interfaces.  That's all fine and lovely and in some distant future I might actually want that functionality.  But the functionality that I want *today*, and don't have, is the ability to write naively for strings.

**Comment by IARI** [comment]
So what is the best workaround if i want logfile to be sys.stdout?

**Comment by jquast** [comment]
Closed by #182 in upcoming 4.0 release,

See https://asciinema.org/a/5k5ouvoz9dynzhrqs63g9opmj
