### ISSUE TITLE
Remaining text is dropped when EOF received

### ISSUE THREAD

**Issue by detly** [pexpect/pexpect#204]
If an EOF is received between finding a match and the caller actually reading it, any remaining text seems to be dropped. (Or perhaps I'm looking for it in the wrong place.)

[This script](https://gist.github.com/detly/d30e7382e6de18d17615) illustrates the problem: I'd expect to see `before: b'Blorp\r'` (depending on the system line endings); instead I see `before: b''`. I'm running that on Ubuntu 14.04.1, in a Python 3.4.0 virtualenv, with pexpect installed from git.

**Comment by jquast** [comment]
Thank you for the script, may be a bug that needs fixing!

**Comment by takluyver** [comment]
Is it in `p.buffer`? I don't think p.before is set until one of the expected patterns is matched.

**Comment by detly** [comment]
1. No, I looked there too.
2. I think the `\n` should be matched, though. It certainly ends up in `p.before` if you set a `pdb` breakpoint in `Expecter.new_data`.

I think the problem is that [`p.before` gets overwritten](https://github.com/pexpect/pexpect/blob/master/pexpect/expect.py#L35) when `Expecter.eof()` is called. This could happen after a match being found, and stored in `p.before`, but before the user has had a chance to read it. But I can't see how to fix it without potentially breaking something else.

**Comment by takluyver** [comment]
As written, I don't think the script you showed is erroneous. `p.before` is the output between the last match from an expect() call, and the current one. Because you're expecting in a loop, it will do something like this:

* Child writes "Blorp\n" to the pty and exits.
* Parent calls expect with `'\n'`. A match is found, `p.before` is set to `"Blorp"` (actually, `"Blorp\r"`, at least on my system, because ptys in cooked mode convert LF to CRLF).
* Parent calls expect with `'\n'`. There is no further match to find, and it hits EOF. `p.before` is set to the output between the last match (`\n`) and EOF. This is empty.

I've checked [the code](https://github.com/pexpect/pexpect/blob/3.x/pexpect/__init__.py#L1544) in Pexpect 3.x, and it appears to do the same thing - EOF is treated as a match even if you didn't pass it to expect(), so it causes `p.before` to be set.

I think this came up in working with the async API, though - is there a condition there where p.before can get discarded from a single expect call? I thought I knew what it was, but when I went to add a test, it didn't fail. :confused:

**Comment by detly** [comment]
[This gist](https://gist.github.com/detly/7e137223e49a0c246960) should show the problem in async usage. My underlying problem is this: say I launch a process and it exits with an error before I can even get to the first `expect()` (or `expect_exact()`) call. How do I see what it printed before it exited?

**Comment by detly** [comment]
Ah, I see the problem in the original script. Adding:

```
            print("1. before: {:s}".format(repr(p.before)))
```

...to the `try` block gives me that info ([see updated gist](https://gist.github.com/detly/d30e7382e6de18d17615)). Same in the `async` one.

**Comment by detly** [comment]
The only other gotcha in this scenario is that you might want to process the whole string, ie. `p.before + p.after` instead of just `p.before`. However, under some circumstances, `p.after` seems to be the `pexpect.exceptions.EOF` object itself (even outside the `except` block), which adds some type checking to caller code. I'll see if I can reproduce this is a smaller script.

**Comment by detly** [comment]
So here's an illustration of the original problem I was having that sent me off on this tangent, and made me think the problem was in the EOF handling.

Take this [C code](https://gist.github.com/detly/efc0572bdd08df041c16) (for some reason I could not produce a Python script that shows the same behaviour). Compile it with `gcc -o weirdness weirdness.c`.

Run [this async pexpect script](https://gist.github.com/detly/4005b18705354dd74811). You should get a traceback:

```
Traceback (most recent call last):
  File "./pexpect_eof.py", line 25, in <module>
    main()
  File "./pexpect_eof.py", line 21, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "./pexpect_eof.py", line 17, in run
    print("1. output: {:s}".format(repr(p.before + p.after)))
TypeError: can't concat bytes to type
```

This is because even in the `else` block, `p.after` is actually the EOF object, and not bytes. I had expected that `p.after` would only ever be data **except** in the `except` block where it's being handled. Is that incorrect? Should callers check for `p.after == pexpect.exceptions.EOF`?

**Comment by detly** [comment]
Incidentally, let's say I try to [account for `p.after`](https://gist.github.com/detly/7ac1a7c1f51e14fc670e) being an EOF exception instead of bytes. I also seem to (a) lose the data I wanted to get in the first place, and (b) get a "Bad file descriptor" traceback:

```
1. output: b'\n'
Traceback (most recent call last):
  File "./pexpect_eof.py", line 33, in <module>
    main()
  File "./pexpect_eof.py", line 29, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "./pexpect_eof.py", line 12, in run
    _ = yield from p.expect_exact('\r', async=True)
  File "/home/jason/Code/pexpect/pexpect/async.py", line 16, in expect_async
    .connect_read_pipe(lambda: PatternWaiter(expecter), expecter.spawn)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 602, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 144, in _make_read_pipe_transport
    return _UnixReadPipeTransport(self, pipe, protocol, waiter, extra)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 258, in __init__
    mode = os.fstat(self._fileno).st_mode
OSError: [Errno 9] Bad file descriptor
```

**Comment by takluyver** [comment]
OK, it does look like a bug to me that `p.after` can be EOF even when it hasn't thrown EOF. I guess that's only when using async, right? I will look into that in more detail tomorrow, but I think I have a good idea what's going on.

The 'bad fd' traceback is, I suspect, because the loop redoes the expect call after the pty has been closed. We should check `flag_eof` and exit early in that case.

I know the before/after API is not the most intuitive thing. There's a note in the [FAQ](http://pexpect.readthedocs.org/en/latest/FAQ.html) about why it is that way, but it's mostly for backwards compatibility now. Perhaps there's an opportunity for someone to develop a similar tool with a clearer API, though I would guess that Pexpect is 'good enough' that users aren't especially motivated to build a replacement.

I wouldn't be surprised if the difference with the C code is just speed - either from the fork to printing output, or from the output to process exit. If you want to play around with exiting from a Python process in a hurry, look at `os._exit()`. If you want to avoid the interpreter initialisation, you could tweak the PtyProcess code to do what you want immediately post-fork rather than exec-ing python.

**Comment by detly** [comment]
I don't find the `before`/`after` API bad at all; it caters to those who want everything but the match, and those who want everything including the match. Perhaps if it were up to me I might have the `expect` or `expect_exact` return something more structured (eg. a tuple with `before` and `after`, or a named-tuple like object with useful information), but as it is I don't really have any problems with it.

**Comment by detly** [comment]
I was going to be clever and re-open this, but I'll just create a new one.
