### ISSUE TITLE
pexpect/bashrc.sh not distributed with pexpect

### ISSUE THREAD

**Issue by jquast** [pexpect/pexpect#280]
needs to be in MANIFEST.in

This is a common problem with testing. My position for preventing such issues is that the 'tests/' sub-folder should move to 'pexpect/tests' and distribute with the package.  Then, use tox to test the package (which installs via pip), and not from the source tree folder(s). This ticket is simply to address the 1 missing file, not to suggest so much work, however :)

**Comment by takluyver** [comment]
Gah, I always forget that one. My solution is to [make my own packaging tool](http://flit.readthedocs.org/en/latest/) that includes data files by default. But it's a fairly opinionated tool, and I don't like to impose it on other developers.

**Comment by jquast** [comment]
See PR #281

**Comment by takluyver** [comment]
BTW, usual practice on Github (on the projects I've seen) is to leave an issue open until the PR with the fix is merged - it's accepting the fix, not proposing it, that means the problem is resolved. If you put 'closes #280' in the commit message, then when the PR is merged, it automatically closes the issue.

If you prefer to work like this, I don't mind, it's just struck me as odd a couple of times when you've closed issues.

**Comment by jquast** [comment]
Sorry, I have a difficult time doing issue tracking on github. Pull requests behave exactly as issues, so it all feels like duplicates to me. The one with the code fix being preferred.

**Comment by takluyver** [comment]
They're very similar, but the projects I work on tend to treat them as two separate categories - problems and potential solutions. Sometimes, one issue might have multiple PRs opened to try to fix it.

**Comment by jquast** [comment]
I try to enforce the issue discussion occurs in serial chronological order of the problem and proposals (PRs) accepted. With all such issues open, the conversation becomes dispersed of open items, like a twitter conversation, impossible to follow :)
