### ISSUE TITLE
spawn() doesn't take cwd into account when resolving relative command path

### ISSUE THREAD

**Issue by de-mux** [pexpect/pexpect#301]
I have a script that needs to call a binary file from a working directory that is not in PATH. However, the spawn constructor does not seem to check the **cwd** argument when determining if the command is executable.
For example, if the executable is **/path/to/my/executable**, calling `spawn('./my/executable', cwd='/path/to')` results in the error:
`The command was not found or was not executable: ./my/executable`

It seems that when cwd is provided, it should also be searched to find the executable, without the need to add the cwd to PATH.

**Comment by takluyver** [comment]
I think this is because the `cwd=` you pass becomes the cwd of the new process, but the path you provide is treated as starting from the cwd of the parent process.

Since you're passing the path to that working directory anyway, it's probably clearest to spawn using `os.path.join('/path/to', 'my/executable')`.

**Comment by de-mux** [comment]
I tried that as well, but it yields the same error.
`The command was not found or was not executable: my/executable`

**Comment by takluyver** [comment]
I mean, construct the full `/path/to/my/executable`, since you have all the parts you need for it.

**Comment by de-mux** [comment]
Oh sorry, I misread your comment. Yes, that does work. But I was thinking it might still be useful to people(as well as possibly less confusing) if spawn took the **cwd** argument into account when constructing the path to the executable.

**Comment by takluyver** [comment]
I guess it may, but there's a risk that it would break code that sets a cwd but finds the executable relative to the current process' cwd.

Either way, I think it's always clearest and safest to turn relative paths into absolute paths as early as possible, rather than relying on where another component will rely on them starting from.

**Comment by de-mux** [comment]
Sounds fair enough. Thanks for clearing that up!

**Comment by takluyver** [comment]
No problem. If it was new code, I think I'd probably go for what you suggest, but for old code, I think the argument for not breaking stuff that already works is stronger.
