### ISSUE TITLE
interact display corrupted

### ISSUE THREAD

**Issue by 2020sebastian** [pexpect/pexpect#314]
```python
def jumpTwice():
        process = pexpect.spawn("ssh -o 'StrictHostKeyChecking no' "+user+"@"+firstHost, maxread=5000)
        process.expect("assword:")
        process.sendline(onePass)
        process.sendline("\r")
        process.sendline("ssh -o 'StrictHostKeyChecking no' "+user+"@"+ secondHost)
        process.expect("assword")
        process.sendline(onePass)
        process.sendline("ssh -o 'StrictHostKeyChecking no' "+systemUser+"@"+userHost)
        process.sendline("\r")
        i = process.expect("assword")
        if i == 0:
            process.sendline(Pass)

        process.sendline("bash")

        try:
            process.interact()
            sys.exit(0)
        except:
            sys.exit(1)
```

Using this to log in to linux boxes and works fine for just navigating around, but when I "less" a larger log file I can't move up and down with arrows, just page up/down, and the output gets corrupted.

After I exit from the boxes and back to my localhost, output stays corrupted (if I do ls -al it will try and overwrite over what's on the screen instead of clearing it)

**Comment by jquast** [comment]
The screen display is corrupted because your window size is not correctly communicated down the chain, the remote end believes you are 80 by 24, the default size, but it is wrong. The original pexpect API does not install a signal handler to "propagate" the size, it suggests that you write that code yourself.

Two options:

- install the code suggested in the docstring, beginning "Note that if you change the window size" ...
 http://pexpect.readthedocs.org/en/stable/api/pexpect.html#pexpect.spawn.interact

- avoid pexpect entirely and make this easier by using standard ssh's ProxyCommand directive with nc(1), see http://undeadly.org/cgi?action=article&sid=20070925181947
