### ISSUE TITLE
pip install error on python2

### ISSUE THREAD

**Issue by IlyaSukhanov** [pexpect/pexpect#318]
Get the following error when running `pip install pexpect` in a clean python2 virtualenv
>Installing collected packages: pexpect, ptyprocess
>  Running setup.py install for pexpect
>      File "/home/user/.virtualenvs/pexpect_test/lib/python2.7/site-packages/pexpect/async.py", line 16
>        transport, pw = yield from asyncio.get_event_loop()\
>                                 ^
>    SyntaxError: invalid syntax

The same command works in python3 virtualenv.

Is python2 supported?

**Comment by takluyver** [comment]
Hi Ilya,

Python 2 is supported: pip shows that error because it tries to byte-compile all the files, and the `pexpect.async` module in particular only works on Python 3. But despite the error message, the install should have succeeded, and pexpect should be usable.

If you upgrade to a recent version of pip, you shouldn't see the error message at all.

**Comment by IlyaSukhanov** [comment]
Thank you so much for clarifying!
