### ISSUE TITLE
How to handle killed process

### ISSUE THREAD

**Issue by egorf** [pexpect/pexpect#324]
Hi!

I recently [asked a question](https://github.com/pexpect/pexpect/issues/322) about killing a process from another thread. 

How do I check if the process was killed or finished correctly by itself? What I did in the first place was to check `child.signalstatus` was not `None` after `child.expect(pexpect.EOF)` occurred. However, that does not  really seem to be stable and sometimes `child.signalstatus` stays `None` after the process is killed. 

Is that how it is supposed to be and I am doing something wrong or is it a bug?
How else can I check if the process was killed? 

Python 2.7.3, Pexpect 3.3

**Comment by takluyver** [comment]
`child.signalstatus` should indicate if it was killed by a signal, but that might not always be what you think it is. E.g. if you send `SIGINT` to a Python process, it raises a KeyboardInterrupt exception which will terminate the program unless it is caught. But in this case, because the signal was handled and didn't directly kill the process, it exits with a normal exit status of `1` for an uncaught exception. Most signals can be caught if the process sets up handlers for them. I think SIGKILL is the only one that terminates the process without any chance for handlers to run.

If you want to check whether the process exited normally, you should check whether the exit status is 0.

**Comment by egorf** [comment]
I am using pexpect to run a C program, sorry, should have mentioned it. But I'll definitely try to check the `exitstatus` instead of `signalstatus`

**Comment by takluyver** [comment]
It's probably best to check both - one will be set to a number, the other should be `None`.

**Comment by egorf** [comment]
Thanks!
