### ISSUE TITLE
segmentation fault occurs

### ISSUE THREAD

**Issue by rowe93** [pexpect/pexpect#364]
```
In [1]: import pexpect

In [2]: pexpect.__version__
Out[2]: '3.3'

In [3]: pexpect.run('ls')
[1]    19957 segmentation fault  ipython
```

**Comment by takluyver** [comment]
Is it reproducible? What platform are you on? What Python version?

It's highly unlikely that Pexpect is causing a segfault by itself, because it's pure Python code; it's probably triggering a bug in something else.

**Comment by lasteye** [comment]
@takluyver Yes, it is reproducible. 
Platform: Gentoo, a  Linux distribution;
Python: Python 2.7.11

**Comment by jquast** [comment]
@lasteye i suspect you have a bad installation rather than a python problem. This segfault is of your Python executable rather than our scripts. Scripts raise exceptions and print trackbacks!

I suggest asking #gentoo on free ode if anyone else can reproduce, and begin with Gentoo package maintainers to debug if it is a reproducible problem.

**Comment by pva** [comment]
This is not expect problem. Please, use patch from here:
https://bugs.gentoo.org/show_bug.cgi?id=584916#c12
