### ISSUE TITLE
windows ssh command in PopenSpawn  opens a popup window to input passowrd 

### ISSUE THREAD

**Issue by jcuan** [pexpect/pexpect#423]
when I use ssh comman in cmd or cmder terminal, the output like this
```
$ ssh jcuan@222.197.xxx.xxx
jcuan@222.197.xxx.xxx's password:
```
However，when in PopenSpawn，the command open a window for me to input passowrd before `expect('*password*')`
```python
from pexpect import popen_spawn
child = popen_spawn.PopenSpawn('ssh jcuan@222.197.xxx.xxx')
child.expect('*password*')
child.sendline('xxxxxx')
child.interact() 
```
E~~maybe it's a hard thing to read my English.... :joy: thanks!

**Comment by takluyver** [comment]
Many programs detect whether they're running in a terminal or with pipes (Popen), and behave differently. With `pty`s on Unix, we can pretend to the process that it's in a terminal and activate that behaviour. But we don't have a good way to do the same on Windows, because there's no equivalent to ptys.

You could look at using wexpect or winpexpect, which use a hackish way to run processes in a Windows console. That is more conceptually similar to what `pexpect.spawn()` does on Unix, but it's some ugly code that I don't want to maintain.

**Comment by takluyver** [comment]
Closing as I think there's nothing practical to be done about this.
