### ISSUE TITLE
Wrong value for crlf when using PopenSpawn

### ISSUE THREAD

**Issue by jeberger** [pexpect/pexpect#488]
When using `PopenSpawn`, `crlf` should be set depending on the OS. However there are two issues in the current code:

- `crlf` is hardcoded to `\n` in the declaration of `PopenSpawn`, which is wrong on Windows.
- but anyway `crlf` is overwritten in the `SpawnBase` constructor so it is always set to `\r\n`, which is wrong on Unix systems.

**Comment by takluyver** [comment]
Oh yes, it should be set in the constructor as well, and the bytes/unicode decision should be based on the `encoding` parameter, like in SpawnBase, not the Python version.

I think it might be right to use `\n` even on Windows, because it's used for `readline()`, and you may want to read a line that ends with `\n` rather than `\r\n`. AFAIK processes can still write to stdout with LF, even if that's not the platform convention.

**Comment by jeberger** [comment]
Processes can write whatever they want on all platforms provided they close stdout and reopen it in binary mode. Otherwise if you do `sys.stdout.write ("\n")` (or whatever is the equivalent in your language), then this will be translated by the std lib and your program will really output `\r\n`. Given the difficulty of forcing stdout in binary mode, I think the default should follow the default platform behaviour (after all if you went to the trouble to force your program output in binary mode, it's no big deal to add the `ctx.crlf = "\n"` in your `pexpect` script).
