### ISSUE TITLE
Wait until child calls read()?

### ISSUE THREAD

**Issue by alkisg** [pexpect/pexpect#557]
Hi, I'm trying to translate an ssh login to a graphical application (display manager) login.
This cannot be easily done by "expecting" specific strings in the output, due to localized versions of messages like "your password has expired, enter a new one:".

I want to wait until the ssh process tries to read() from the tty, at which point my process will get all the ssh output, isolate the last line (e.g. enter a new password), and show it as is to the GUI.

So my question is, **does the pexpect library have a hook for that? "Wait until child calls read()"?**

**If not, here's an implementation idea:**
- We create a new process group with a tty.
- We run the ssh process as a **background** process in that group.
- This will allow the ssh to write() to the tty, but will put it at a stopped state at the moment it tries to read() from it (SIGTTIN).
- So our parent process can poll until ssh enters the stopped state, which would mean that it finished its output and is currently read()ing.

If the above idea is worth exploring, I could try contributing some code, even though I'm not very familiar with process and tty management.

References: http://www.linusakesson.net/programming/tty/

**Comment by takluyver** [comment]
That sounds clever, but it also sounds like significant extra complexity. Pexpect is enough to maintain already, and it has to maintain backwards compatibility because it's been in use for so long already.

So I'd encourage you to write this yourself and release it as a separate project. You can design your own API, set your own release schedule, and generally not be burdened by having to integrate it with Pexpect's code, where we have to be much more conservative. If it's useful, we can link to it from the pexpect docs, like we do for paramiko.

**Comment by alkisg** [comment]
Thank you takluyver, will do.

**Comment by takluyver** [comment]
Thanks. Please do drop a link here when you've got something; I'd be interested to have a look.

**Comment by alkisg** [comment]
Just as a follow-up, I managed to use SSH_ASKPASS, so there was no need for screen-scraping at all.
