### ISSUE TITLE
PopenSpawn.send() send using Windows keypress events

### ISSUE THREAD

**Issue by th3coop** [pexpect/pexpect#569]
I'm current using Pexpect to implement tests for a CLI tool.  On Windows I've come across an issue where the library we are using to receive input from an interactive user interprets Stdin based on keypress events from Windows.  I'm not clear what the motivation was for the library writer to do this but it obviously breaks when Pexpect writes direct to stdin of the spawned process.

I'm wondering if the maintainers of pexpect have come across this use case before.  If yes, have you done any research into a viable solution yet?  Is there a plan to add support for this?  Any pointers or advice you could share on working though this issue so I can keep using Pexpect I'm currently attempting to use [pynput](https://pynput.readthedocs.io/en/latest/) to simulate keypress.  It's not working so far but I've only done a very basic trial.

Hope that makes sense.  Any input would be appreciate and thanks in advance.

**Comment by takluyver** [comment]
Have a look at: https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

winpexpect or wexpect might be able to do what you want. But they're unmaintained (last time I checked, anyway), and they do something much more complex and fiddly than PopenSpawn, which is why I've resisted trying to pull this functionality into Pexpect itself.

**Comment by th3coop** [comment]
Thanks for the ref., @takluyver.  I had a look and as you said it is really old code.  I had a go at trying to integrate it with what we have but I'll need more time than what I have at the moment.  Thanks for the input though, much appreciated!
