### ISSUE TITLE
Is using pexpect.TIMEOUT a valid workaround for expect() ?

### ISSUE THREAD

**Issue by thisdougb** [pexpect/pexpect#639]
#### Context
I might just be missing something (I have read through the expect module).  I'm setting up pexpect.spawn sessions through a class which takes a prompt string.  So the cli prompt is not fixed, it's set when the session starts.

When I use expect() I'm having trouble finding a regex pattern that works consistently, and easily.  Say something simple like, "$ ".  I need to put that through a function to apply escapes and turn it into "\\\\$ ".

When using:
```
session.sendline("cat test_file")
session.expect("$ ")
response = session.before.rstrip()
print("RESPONSE ", response)
```
I get old data from the buffer (here the zsh warning from bash login on OSX):
```
RESPONSE  
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ $
```
It gets more difficult when an "$ " appears in some text, perhaps in a "cat somefile.txt":
```
$ cat test_file 
hello
dollar $  .
goodbye
$ 
```
My pexpect("\\\\$ ") picks this out, which is not what I want:
```
buffer (last 100 chars): '.\r\ngoodbye\r\n'
before (last 100 chars): 'hello\r\ndollar '
after: '$ '
match: <re.Match object; span=(14, 16), match='$ '>
```
#### Question
So I am wondering if, to be able to read the current response immediately after a sendline() I should just be using TIMEOUT as the pattern?
```
session.sendline("cat test_file")
session.expect(pexpect.TIMEOUT, timeout=-1)
print(session)
response = session.before.rstrip()
print("RESPONSE ", response)
```
This gives me the end result I want:
```
<snipped>
buffer (last 100 chars): 'hello\r\ndollar $ .\r\ngoodbye\r\n$ '
before (last 100 chars): 'hello\r\ndollar $ .\r\ngoodbye\r\n$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: <class 'pexpect.exceptions.TIMEOUT'>
match_index: 0

RESPONSE  hello
dollar $ .
goodbye
$
```
Unfortunately the timeout cannot be bypassed, so I always have a 1 second pause.

Are there any bad side-effects of using TIMEOUT to do this?  I guess this is functionality like a real-time version of read().

**Comment by thisdougb** [comment]
I think I see where I misunderstood things.

```
buffer = "/etc/hosts\r\n"
pattern = "\r\n"
```
running expect(pattern) gives:
```
before = "/etc/hosts"
after = "\r\n"
buffer = ""
```
So 'after' consumes the pattern string.  I got it into my head that 'after' had the remainder of the string (buffer).

I'm now using this to consume the output of a sendline(c):
```
session.sendline(c)
while True:
    session.expect(["\r\n", pexpect.EOF, pexpect.TIMEOUT])
    print(session.before)
    if not session.buffer:
        break
```

**Comment by vivintsmartvideo** [comment]
I like what you were trying with:
`session.expect(pexpect.TIMEOUT, timeout=-1)`
but setting the timeout=-1 would use your default timeout, that must be the 1 second delay you are seeing.  I think instead you should have a timeout of 0 to not wait
`session.expect(pexpect.TIMEOUT, timeout=0)`

**Comment by Red-M** [comment]
I'll chime in because these hacks are not helpful in my opinion and should be addressed.
Generally, you'll want a good prompt to use.

An example of a dynamic prompt is Cisco IOS devices which change the prompt around based on what sub-menu you're in.
example prompts:
```
hostname>
hostname#
hostname(config)#
hostname(config-line)#
hostname(config-if)#
```

So a matching regex for that "moving" prompt is `hostname(\(.+?\)|)[>#]` (there are better ways to do this, including automatically grabbing the hostname to inject into the regex with an `re.escape()` call)

For your context however, I'd start my session with a `session.sendline('')` to get a full prompt back and expect for a "simple" prompt such as just `'$'` so that you can get a full prompt for expecting down the line. This way you don't have a chance of getting unexpected prompts with just `'$'` as the prompt and you're ensured to never need to change the prompt as long as the prompt is static (which for this bash terminal is true).

Prompt acquisition is not an included part of the library because frankly, its all just text/strings all the way down. If you want some more examples for prompts take a look at projects such as RANCiD, oxidized or netmiko, they all have "drivers" for different devices (which are all basically different shells and therefore different prompt methods and strategies).

What I'm mainly trying to put emphasis on here is that you need to:
- Pick good regexes for prompts/`expect()`
- Think about corner cases in what text could show up in the buffer
- Sometimes the terminal/pty/program itself can actually provide you the prompt

**Comment by thisdougb** [comment]
> I like what you were trying with:
> `session.expect(pexpect.TIMEOUT, timeout=-1)`
> but setting the timeout=-1 would use your default timeout, that must be the 1 second delay you are seeing. I think instead you should have a timeout of 0 to not wait
> `session.expect(pexpect.TIMEOUT, timeout=0)`

Hi,

Setting to 0 (from memory) means block/wait forever.  So effectively no-timeout.

**Comment by thisdougb** [comment]
@Red-M ,

thanks for the detailed response.

What I’m doing is replaying a supplied (variable) set of commands, some of which alter the prompt.  So the commands are not fixed, nor are the prompts.  As an example, going into the Python interactive interpreter, and back to the system prompt, is a challenge for regex.

For example:
```
commands:
    - python3 --version
    - python3:
        - python3
        - import secrets
        - secrets.token_hex(16)
        - CTRL_D
    - whoami
    - ssh user@remote.comm
        - cd /etc
        - exit
    - export PS1='mynewprompt > '
    - cat 
```

The other thing I didn’t fully understand was how pexecpt reads from the input stream.  But as I cloned pexepct and added some debug into it, that became clear.  And this brought up a second problem that was causing me a problem.

It seemed that ‘new data’ was arriving on the pexepct stream (response text for processing by expect()), after I’d run through my 'while:True' loop and cleared the buffer.  So, in my code, I’d read the response, cleared the buffer and moved on to sending the next line.  But my code was running faster than the response data was filling the pexpect stream buffer.

So I added a delay after sendline(), and that makes things much more consistent.  Also, expect_exact() which solved some special char escaping problems.  So, now, I’m using this, where I pass a dict into the method with the context:
```
    delay = 0.2  # 0.1 was not long enough, probably system dependent
    command = handler_data["command"]
    session = handler_data["local"]
    prompt = handler_data["config"]["prompt-string"]

    session.sendline(command)
    time.sleep(delay)
    while True:
        session.expect_exact([prompt, '\r\n', pexpect.EOF, pexpect.TIMEOUT])
        if session.before.rstrip():
            print(session.before.rstrip())
        if not session.buffer:
            break
```
As I now realise, pexect can’t know when the shell session has finished sending back response data.  Which is, by design, why the prompt is used as a separator (of the stream data).  

```
$ cat test_file
# a test file
I want a prompt $ like that
$
```
As a stream this looks like, delivered to the buffer char by char:
```
$ cat test_file\r\n# a test file\r\nI want a prompt $ like that\r\n$
```
Possible buffer contents for expect() to search:
```
buffer: $ cat test_file\r\n# a 
buffer: $ cat test_file\r\n# a test file\r\nI want a prompt $ li
```
So when the prompt is unknown before you start, and may change during the session, it’s hard.  I don’t really have an answer, beyond the 0.2 delay which seems to help a lot for me.

I really like pexepct, and the way it’s been developed given the challenges.  What I would like, and may develop in my own fork of pexect, is a way to dump the full buffer.  So I could send my command, then send a (hidden) trailing echo status (I already do this).  So using a uniq id rather than a prompt string as the stream delimiter.

Something like:
```
    session.delay_after_send = 0.2
    uniq_id = secrets.token_hex(5)

    session.sendline(command)
    time.sleep(delay)
    session.sendline(“echo $?-{0} “.format(uniq_id))
    stream_str = session.dump_buffer(wait_for=uniq_id)
```
I dunno yet, lots to learn 😀

**Comment by thisdougb** [comment]
A bit more context.  I did quite a bit of training/video-docs in the past couple of years.  And built a python module to automate the cli portion of the work, which I'd screen-record, and the splice into a video.  Which means I can avoid typos, get consistent timing, etc, for the video production.  It saves a huge amount of time.

a short example: https://vimeo.com/409842928

Hopefully next week I'll push the module (now refactored and tidied up) into PyPI.

**Comment by Red-M** [comment]
If you're doing that kind of work, I'd recommend making modifications to ansible and it's modules to handle talking to everything (by just adding a command output to stdout). Pexpect isn't able to handle that kind of operation gracefully in my opinion and unless you're looking to build an [expect parser](https://en.wikipedia.org/wiki/Expect#Usage) you're not going to have a fun time handling all the edge cases automatically.

I've professionally used pexpect to build automation systems for large scale deployments and that kind of system always required device "drivers" to get properly interfaced with the remote system/environment. They were not exactly pretty but generally short and sweet.
(if you're interested, I've since built a replacement library to pxssh (since you're using ssh commands) which is on my profile).

**Comment by thisdougb** [comment]
Yeah, I use Ansible a lot.  But it's not right for this.  I'm not trying to implement automation of 'work' (for which I do use Ansible), but to show how things are done for people who are learning.  For example, a video-tutorial to show how to setup password-less ssh.  The typing of the commands matters.

So it's not a module for coding (per se), but just load commands or a yaml file of commands:
```
dougb % python3
Python 3.8.2 (default, Mar 11 2020, 00:29:50) 
>>> import typetastic
>>> robot = typetastic.Robot()
>>> robot.load(["ls", "whoami"])
>>> robot.run()
$ ls
MagicMousePower.sh
a.txt			b.txt
$ whoami
dougb
$ 
dougb %
```
I'll have a read through your module, thanks 👍
