### ISSUE TITLE
Feature Request: Implement ContextDecorator for pxssh

### ISSUE THREAD

**Issue by mrdgo** [pexpect/pexpect#670]
# Current state
Currently you have to do:

```python
client = pxssh.pxssh()
client.login('IP ADRESS', 'USERNAME')

# Use the session

client.logout()
```

# Request
With very small changes to the class `pxssh`, one could achieve:

```python
with pxssh.pxssh('IP ADDRESS', 'USERNAME') as client:
    # use the session
```

[Implementation documentation](https://docs.python.org/3/library/contextlib.html#using-a-context-manager-as-a-function-decorator)

# Reasoning

## Simplicity

1. One line of code is simpler to read than three.
2. It is simpler to understand the code, when all the config is passed to the constructor of a class.

## Error proof

1. It is easy to forget to logout from a session.
2. It is nearly impossible to not exit a block.

**Comment by Red-M** [comment]
I heavy do not encourage the use of pxssh anymore as alternate solutions work way better in many aspects. [As per the notice on the documentation](https://pexpect.readthedocs.io/en/stable/api/pxssh.html)

This doesn't add very much and makes pxssh much more complicated and its not that clean because try to put actual values into that example of using the `with` context. The line will be HUGE in some use cases and will spill over many lines.
So its better to allow people to build their options and then log in to remote machines when they need to.
