### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by oz123** [pexpect/pexpect#718]
@takluyver is it possible for you or any other maintainer to cut a new release?

Pipenv and Poetry suffer from similar  issues using the current version on pypi with windows. I was thinking maybe a new
version has these issues fixed already.

https://github.com/pypa/pipenv/issues/4396#issuecomment-1105555438

**Comment by Red-M** [comment]
As per [the installation documentation](https://github.com/pexpect/pexpect/blob/2be6c4d1aa2b9b522636342c2fd54b73c058060d/doc/install.rst#requirements), there are limitations for windows when using pexpect compared to linux.

That issue doesn't include enough information (or anything that references that pexpect is having issues) for me to debug it without significant effort trying to do what they were doing.
If more information were presented about what is going on and why this is an issue that pexpect is causing I could debug this further.

With all that in mind I can't say if a new release would help with that problem. Anyone is able to install pexpect's `master` branch to test if any changes since the last release have fixed the problem.
