### ISSUE TITLE
Issues and our ability to handle them

### ISSUE THREAD

**Issue by Red-M** [pexpect/pexpect#731]
@dluyer @jdemeyer @jquast @noahsquaretrade @takluyver 
I'd like to get the number of open issues down to <20.
Can we please discuss what we're happy with to handle issues?

I'd like to open the github discussions feature and move issues around user questions or help there so we can keep the issues only related to software problems in pexpect in the issues section.
This way other users can help each other and we can keep a more clear idea about when other projects find problems or someone wishes to request features.

I don't like stale bots that auto-close because it feels like a complete lack of responsibility and ownership on problems as you can simply wait out the timer to not answer difficult questions. I am however happy to put this in if other people would prefer to have such a process.

**Comment by jquast** [comment]
- sorry for the 19-day delay, I am doing my best to retun to FOSS work and balance against demanding $DAYJOBS, it gets harder as I get older
- I do like to use the github label feature. That's the first thing I'm looking to do, and of course, to focus on bugs. I sometimes wonder about questions, especially as they age, most people aren't interested in an answer after just a few days, they move on or find another solution, as a volunteer with limited time, I really can't afford to answer questions or provide example code.
- We're very low-volume volunteers, we should probably spell that out somewhere front and center, and maybe move this suggestion to [use stackoverflow](https://github.com/pexpect/pexpect/blob/2be6c4d1aa2b9b522636342c2fd54b73c058060d/doc/FAQ.rst#faq) on the main page.
- I still prefer to direct people to SO, it only improves over time and contains many of examples and existing solutions. But anyway I'm not attached to it, whatever provides the best value for the developers who use pexpect.
- I also don't like any bots closing any issues.

Personally, for this project, I would like to,
- mark pexpect as "maintenance only mode", no new features!
- direct people to alternate solutions (streamexpect and asyncssh/paramikko)
- fork and improve streamexpect with asyncio and pty support
- Continue to try to support latest python and drop older versions as necessary, for example 3.11 currently fails with asyncio due to use of old-style asyncio, and use "python_requires" so that older python versions automatically install older releases of pexpect.

Hope this is helpful to the conversation, best wishes.

**Comment by Red-M** [comment]
Not really fussed about the delay, thank you for replying, as I do also struggle with the same issue (and balancing my own time to relax and enjoy myself).

>We're very low-volume volunteers, we should probably spell that out somewhere front and center, and maybe move this suggestion to [use stackoverflow](https://github.com/pexpect/pexpect/blob/2be6c4d1aa2b9b522636342c2fd54b73c058060d/doc/FAQ.rst#faq) on the main page.
I still prefer to direct people to SO, it only improves over time and contains many of examples and existing solutions. But anyway I'm not attached to it, whatever provides the best value for the developers who use pexpect.

I'm not so sure on SO but could we have both? SO and GH discussions? Its hard to answer some questions because I don't have an OSX machine or some particular program or network setup to replicate issues that users submit, plus sometimes its better to not answer and let them figure their own issue out because its trivial (which is good for everyone because they learn how to fix their own problems).


> mark pexpect as "maintenance only mode", no new features!

I don't mind keeping pexpect open to new things because it works well and if there is a good feature that someone wishes to add that we could see a lot of people liking, then why not?

>direct people to alternate solutions (streamexpect and asyncssh/paramikko)

I do agree we should depreciate pxssh, its not really that good at handling SSH because of all the missing protocol level stuff that other libraries (including my own) have. In saying that though, I also have a library that fits the need of an expect abstraction with very little overhead and a bit of modularity. While I did take a look at streamexpect, it seems a little quiet and that it doesn't have a lot of active people around it.

I also don't like the prospect of duplicating or throwing work over the fence to other projects because pexpect doesn't need much more work IMO, it needs maintenance but isn't a "we're deprecating this and its maintenance only mode" situation. If something is simple and I can sort it out with <3 minutes of interaction, I normally do it (but not a lot of things recently have been around that threshold so far).

I think for pexpect itself, it might be better to discuss further about it as I'm wanting to keep this project alive.

>fork and improve streamexpect with asyncio and pty support

I think ptyprocess (and iirc) does most of the abstraction for pty support so even something as simple as my own redexpect should be able to work with ptys or even the same as streamexpect (since all redexpect requires is a `.read()` and a `.write()` or `.send()`)

>Continue to try to support latest python and drop older versions as necessary, for example 3.11 currently fails with asyncio due to use of old-style asyncio, and use "python_requires" so that older python versions automatically install older releases of pexpect.

In that vein, I'd like to drop our older version support and there is #732 which is a really good PR IMO, but I haven't had the proper time yet to really review it properly (also the fact that test results are no longer showing up in the PRs so I need to fix that too)

**Comment by piraz** [comment]
I agree with the your view about #732, @Red-M. This function is really import because even streamexpect has no support to asyncio.

See: https://github.com/digidotcom/python-streamexpect/issues/1.

Their ticket is pointing to the solution implemented by you guys. Still think the pexpect is the better solution to control control an application from another application.

> (also the fact that test results are no longer showing up in the PRs so I need to fix that too)

What about move the testing to github actions instead of on travis?

**Comment by swt2c** [comment]
I would be happy to port the CI to run on GitHub Actions, if that's what you would like.

**Comment by swt2c** [comment]
> I would be happy to port the CI to run on GitHub Actions, if that's what you would like.

@Red-M I went ahead and ported the CI to use Github Actions.  Hopefully it will be helpful: #734

**Comment by Red-M** [comment]
> > I would be happy to port the CI to run on GitHub Actions, if that's what you would like.
> 
> @Red-M I went ahead and ported the CI to use Github Actions. Hopefully it will be helpful: #734

Thanks! I've merged that.



> I agree with the your view about #732, @Red-M. This function is really import because even streamexpect has no support to asyncio.
> 
> See: [digidotcom/python-streamexpect#1](https://github.com/digidotcom/python-streamexpect/issues/1).
> 
> Their ticket is pointing to the solution implemented by you guys. Still think the pexpect is the better solution to control control an application from another application.
> 
> > (also the fact that test results are no longer showing up in the PRs so I need to fix that too)
> 
> What about move the testing to github actions instead of on travis?

Yeah, GHA seems to be the easiest for this now, I also want to get this into gitlab CICD as well, so that we're tied to a single and *aaS provider.

**Comment by karrukola** [comment]
Hello all,
I am willing to provide support, for instance to address PRs and triage issues.
We could allocate time of one of my team members for a day a week in the next 3 to 6 months.

Please let me know if you would like to discuss it further.

**Comment by Red-M** [comment]
I'm happy for anyone to provide PRs at any time, as reviewing a PR is much more efficient for me now that we have tests running via github actions.

I do passively watch the github issues as I get emails for everything that goes on with pexpect, if I see something I can sort out within an hour after work that day, I generally do.

**Comment by Red-M** [comment]
I'll close this out after 6 months of time if no new responses come in from any maintainers.

**Comment by Red-M** [comment]
I'm going to take the silence as agreement.
