### ISSUE TITLE
4.9.0: git tag does not match PyPI version

### ISSUE THREAD

**Issue by mtelka** [pexpect/pexpect#781]
The recently released version `4.9.0` (see https://pypi.org/project/pexpect/4.9.0/) seems to be tagged in git as [4.9](https://github.com/pexpect/pexpect/releases/tag/4.9).    Please use same versioning scheme for git tags and PyPI releases to avoid confusion.

Thank you.

**Comment by Red-M** [comment]
I did this because I actually tagged 4.7 incorrectly as 4.7.0 and another maintainer did the same (most likely copying my previous release) after that for 4.8. If you look at the previous releases, they are all tagged the same and the release notes reference them as such.

I'm happy to make the change if you can find something that reinforces this in our issues or PRs as the version is tagged this way in the package files for PyPI as they require such versioning but as far as I can see, historically, releases in our git should be tagged the way they currently are.

**Comment by mtelka** [comment]
@Red-M, I'm not sure I fully understand.  It looks like you want versioning scheme `X.Y` (like `4.9`), but versions at PyPI are `X.Y.Z` (like `4.9.0`).  If you really want `X.Y`, then why do you set [`__version__`](https://github.com/pexpect/pexpect/blob/master/pexpect/__init__.py#L84) to `4.9.0`?  I suggest to set `__version__` to the same value as your git tag.  I believe you can safely set it to `4.9`, or `4.10` and PyPI should be okay with that.  At least there are [other projects](https://pypi.org/project/tornado/) with `X.Y` versioning scheme (and `tonado` is not the [only one](https://pypi.org/project/ConfigUpdater/) such project; actually, you can find [many such projects](https://pypi.org/project/gi-docgen/)).

Thank you.
